name: Conda job

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  create-env:
    name: Ex4 Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: foo
          python-version: 3.8s
          channels: conda-forge
          allow-softlinks: true
          channel-priority: flexible
          show-channel-urls: true
          use-only-tar-bz2: true
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda install -c conda-forge xesmf pip
          conda install -c conda-forge xesmf esmpy=8.0.0
          conda install -c conda-forge esmpy xarray scipy dask netCDF4
          conda install -c conda-forge matplotlib cartopy xgcm jupyter jupyterlab
          pip install pytest
          pytest -v --pyargs xesmf
          conda list
      #     pip install git+git://github.com/kthyng/xcmocean
      #     pip install git+git://github.com/hetland/xroms
