name: Conda job

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  
  create-env:
    name: Prepare environment
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v3
   
      - uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: false
          environment-name: XROMS
          extra-specs: |
            python=3.8
          channels: conda-forge
      - run: |
          conda install -c conda-forge xesmf esmpy=8.0.0 pip
          conda install -c conda-forge xarray scipy dask netCDF4
          conda install -c conda-forge matplotlib cartopy xgcm jupyter jupyterlab
          conda install -c xcmocean
          pip install git+git://github.com/hetland/xroms
  test-code:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    needs: [create-env]
    steps:
      - uses: actions/checkout@v3        
      - uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: false
          environment-name: XROMS
          extra-specs: |
            python=3.8
          channels: conda-forge
      - run: |
          pip install pytest
          pytest -v --pyargs xesmf
