name: Conda job

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  create-env:
    name: Prepare environment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v2    
      - uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: false
          environment-name: XROMS
      - run: |
          micromamba create --yes --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt --channel conda-forge
          pip install git+git://github.com/hetland/xroms
  test-code:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash -el {0}
    needs: [create-env]
    steps:
      - uses: actions/checkout@v2         
      - uses: mamba-org/provision-with-micromamba@v13
        with:
          activate-environment: XROMS
          allow-softlinks: true
          channel-priority: flexible
      - run: |
          pip install pytest
          pytest -v --pyargs xesmf
