name: Conda job

#############################
# Start the job on all push #
#############################
on:
  push:
    # branches-ignore: [master, main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, main]

jobs:
  create-env:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04,ubuntu-20.04]
        python-version: ["3.8","3.9"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          name: xoceanmodel/xroms

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@v13
        with:
          environment-file: false
          persist-credentials: false     

      - name: install
        shell: bash -l {0}
        run: |
          micromamba create --yes --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt --channel conda-forge
          micromamba activate TEST
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/xoceanmodel/xroms
          python -m  pip install git+git://github.com/hetland/xroms

      # - name: test xesmf installation
      #   shell: bash -l {0}
      #   run: |
      #     micromamba activate TEST
      #     python -m pytest --cov=./ --cov-report=xml --verbose
